# Generated by Django 2.2 on 2020-08-23 19:10

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_assistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='photos/%Y/'),
        ),
    ]
