# Generated by Django 2.2 on 2020-08-29 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200829_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_requested', models.DateTimeField(auto_now=True, verbose_name='requested on')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Rejected')], default='P', max_length=1, verbose_name='status')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Guide', verbose_name='')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Team', verbose_name='')),
            ],
        ),
    ]
